### ISSUE TITLE
[CRASH] 2nd random crash in the past 10 minutes

### ISSUE THREAD

**Issue by CallMeDaBest** [Rebirth-of-the-Night/Rebirth-Of-The-Night#438]
**Describe the crash**

**To Reproduce**
Steps to reproduce the behavior: Not sure everyone was at home when it happened or running around the world

**Crash Log 1**
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2020-08-02 22:39:06 EDT
Description: Exception in server tick loop

Wrong Minecraft Versions!
Mod: quickteleports
Location: ./mods/quickteleports-1.15.2-1.1.2.jar
Expected: [1.13,)
Current: Minecraft 1.12.2

net.minecraftforge.fml.common.WrongMinecraftVersionException: Wrong Minecraft version for quickteleports
    at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:252)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.15.0-108-generic
  Java Version: 1.8.0_242, Oracle Corporation
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 178804304 bytes (170 MB) / 834142208 bytes (795 MB) up to 5726797824 bytes (5461 MB)
  JVM Flags: 2 total; -Xms128M -Xmx6144M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 200 mods loaded, 200 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                           | Version                  | Source                                                    | Signature |
       |:----- |:-------------------------------------------- |:------------------------ |:--------------------------------------------------------- |:--------- |
       | L     | minecraft                                    | 1.12.2                   | minecraft.jar                                             | None      |
       | L     | mcp                                          | 9.42                     | minecraft.jar                                             | None      |
       | L     | FML                                          | 8.0.99.99                | server.jar                                                | None      |
       | L     | forge                                        | 14.23.5.2847             | server.jar                                                | None      |
       | L     | ivtoolkit                                    | 1.3.3-1.12               | minecraft.jar                                             | None      |
       | L     | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                             | None      |
       | L     | bnbgamingcore                                | 0.11.0                   | minecraft.jar                                             | None      |
       | L     | foamfixcore                                  | 7.7.4                    | minecraft.jar                                             | None      |
       | L     | futuremccore                                 | 0.1.12                   | minecraft.jar                                             | None      |
       | L     | randompatches                                | 1.12.2-1.21.0.3          | randompatches-1.12.2-1.21.0.3.jar                         | None      |
       | L     | aactadapter                                  | 1.12.2-0.1.0             | aactadapter-1.12.2-0.1.0.jar                              | None      |
       | L     | advancedliftingmethods                       | 1.0.0                    | AdvancedLiftingMethods-1.12.2-1.0.0.jar                   | None      |
       | L     | advancedmotd                                 | 1.1.0                    | AdvancedMotd-MC1.12.2-1.1.0.jar                           | None      |
       | L     | aeble                                        | 1.2.0                    | aeble_v1.4.0.jar                                          | None      |
       | L     | aether_legacy_addon                          | 1.12.2-v1.2.3            | aether_continuation-1.12.2-v1.2.3.jar                     | None      |
       | L     | aether_legacy                                | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                           | None      |
       | L     | aiimprovements                               | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                           | None      |
       | L     | animania                                     | 1.7.3                    | animania-1.12.2-1.7.3.jar                                 | None      |
       | L     | antiqueatlas                                 | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                             | None      |
       | L     | anvilpatch                                   | 1.0.0                    | anvilpatch-1.0.0.jar                                      | None      |
       | L     | applecore                                    | 3.4.0                    | AppleCore-mc1.12.2-3.4.0.jar                              | None      |
       | L     | appleskin                                    | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                                | None      |
       | L     | arcanearchives                               | 0.2.0.19                 | arcanearchives-0.2.0.19.jar                               | None      |
       | L     | athenaeum                                    | 1.12.2-1.18.1            | athenaeum-1.12.2-1.18.1.jar                               | None      |
       | L     | atop                                         | 1.5                      | ATOP-1.12.2-v.1.5.jar                                     | None      |
       | L     | attributefix                                 | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                             | None      |
       | L     | autoreglib                                   | 1.3-32                   | AutoRegLib-1.3-32.jar                                     | None      |
       | L     | base                                         | 3.13.0                   | base-1.12.2-3.13.0.jar                                    | None      |
       | L     | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                                    | None      |
       | L     | betterwithaddons                             | 0.51                     | Better With Addons-0.51.jar                               | None      |
       | L     | bettercaves                                  | 1.12.2                   | bettercaves-1.12.2-1.6.0.jar                              | None      |
       | L     | bettercombatmod                              | 1.5.6                    | BetterCombat-1.12.2-1.5.6.jar                             | None      |
       | L     | betternether                                 | 0.1.8.6                  | betternether-0.1.8.6.jar                                  | None      |
       | L     | betterwithlib                                | ${version}               | BetterWithLib-1.12-1.5.jar                                | None      |
       | L     | betterwithmods                               | 1.12-2.3.23              | BetterWithMods-1.12-2.3.23.jar                            | None      |
       | L     | biomesoplenty                                | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar             | None      |
       | L     | biometweaker                                 | 3.2.354                  | BiomeTweaker-1.12.2-3.2.354.jar                           | None      |
       | L     | blockdropstweaker                            | 2.4                      | BlockDropsTweaker-1.12.2-2.4.jar                          | None      |
       | L     | bnbgaminglib                                 | 2.17.6                   | BNBGamingLib-1.12.2-2.17.6.jar                            | None      |
       | L     | bookshelf                                    | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                              | None      |
       | L     | bountifulbaubles                             | 0.0.1                    | Bountiful Baubles-1.12.2-0.1.6.jar                        | None      |
       | L     | bountiful                                    | 2.2.2                    | Bountiful-2.2.2.jar                                       | None      |
       | L     | carryon                                      | 1.12.3                   | CarryOn MC1.12.2 v1.12.3.jar                              | None      |
       | L     | cd4017be_lib                                 | 6.4.17                   | CD4017BE_lib-1.12.2-6.4.18.jar                            | None      |
       | L     | charm                                        | 1.12.2-1.3.7             | Charm-1.12.2-1.3.7.jar                                    | None      |
       | L     | charset                                      | 0.5.6.4                  | Charset-Lib-0.5.6.4.jar                                   | None      |
       | L     | chutes                                       | 1.0.0                    | chutes-1.12.2-1.0.0.jar                                   | None      |
       | L     | clumps                                       | 3.1.2                    | Clumps-3.1.2.jar                                          | None      |
       | L     | contenttweaker                               | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                           | None      |
       | L     | controlledburn                               | 1.12.2.020               | Controlled Burn-1.12.2.020.jar                            | None      |
       | L     | copypaste                                    | 1.1                      | copypaste-1.1.jar                                         | None      |
       | L     | coralreef                                    | 2.0                      | CoralReef-2.5-1.12.2.jar                                  | None      |
       | L     | extendedrenderer                             | v1.0                     | coroutil-1.12.1-1.2.37.jar                                | None      |
       | L     | coroutil                                     | 1.12.1-1.2.37            | coroutil-1.12.1-1.2.37.jar                                | None      |
       | L     | configmod                                    | v1.0                     | coroutil-1.12.1-1.2.37.jar                                | None      |
       | L     | corpsecomplex                                | 1.0.10.1                 | corpsecomplex-1.12.2-1.0.10.1.jar                         | None      |
       | L     | cosmeticarmorreworked                        | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar                      | None      |
       | L     | craftstudioapi                               | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar        | None      |
       | L     | crafttweaker                                 | 4.1.20                   | CraftTweaker2-1.12-4.1.20.576.jar                         | None      |
       | L     | crafttweakerjei                              | 2.0.3                    | CraftTweaker2-1.12-4.1.20.576.jar                         | None      |
       | L     | cyclicmagic                                  | 1.20.2                   | Cyclic-1.12.2-1.20.2.jar                                  | None      |
       | L     | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar                       | None      |
       | L     | diethopper                                   | 1.1                      | diethopper-1.1.jar                                        | None      |
       | L     | disenchanter                                 | 1.6                      | disenchanter-[1.12]1.6.jar                                | None      |
       | L     | doggytalents                                 | 1.15.1.5                 | DoggyTalents-1.12.2-1.15.1.5.jar                          | None      |
       | L     | dropt                                        | 1.12.2-1.18.0            | dropt-1.12.2-1.18.0.jar                                   | None      |
       | L     | dungeontactics                               | DT-0.16.6                | DungeonTactics-1.12.2-0.16.6.jar                          | None      |
       | L     | dsurround                                    | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar                    | None      |
       | L     | dynamictrees                                 | 1.12.2-0.9.8             | DynamicTrees-1.12.2-0.9.8.jar                             | None      |
       | L     | dynamictreesbop                              | 1.12.2-1.4.1e            | DynamicTreesBOP-1.12.2-1.4.1e.jar                         | None      |
       | L     | dynamictreesphc                              | 1.12.2-1.4.2             | DynamicTreesPHC-1.12.2-1.4.2.jar                          | None      |
       | L     | dynview                                      | 1.3                      | dynviewdist-1.12-1.3.jar                                  | None      |
       | L     | eguilib                                      | 0.1.2                    | eguilib-0.1.2.jar                                         | None      |
       | L     | eplus                                        | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                         | None      |
       | L     | enchcontrol                                  | 1.1.5                    | enchcontrol-1.12.2-1.1.5-0.jar                            | None      |
       | L     | endreborn                                    | 0.3.7                    | EndReborn III [0.3.7].jar                                 | None      |
       | L     | epicsiegemod                                 | 13.168                   | EpicSiegeMod-13.168.jar                                   | None      |
       | L     | extendeddays                                 | 0.2.9                    | ExtendedDays-1.12.2-0.2.9-28.jar                          | None      |
       | L     | extraalchemy                                 | 0.5.4                    | extraalchemy-forge-1.12-build11-0.5.4.jar                 | None      |
       | L     | golems                                       | 7.1.9                    | ExtraGolems-1.12-7.1.9.jar                                | None      |
       | L     | fairylights                                  | 2.1.10                   | fairylights-2.1.10-1.12.2.jar                             | None      |
       | L     | fantasticlib                                 | 1.12.2.034               | FantasticLib-1.12.2.034.jar                               | None      |
       | L     | fastfurnace                                  | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                              | None      |
       | L     | fastbench                                    | 1.7.3                    | FastWorkbench-1.12.2-1.7.3.jar                            | None      |
       | L     | mod_lavacow                                  | 1.0.13                   | Fishs_Undead_Rising-1.0.13.jar                            | None      |
       | L     | foamfix                                      | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                                | None      |
       | L     | forgelin                                     | 1.8.4                    | Forgelin-1.8.4.jar                                        | None      |
       | L     | minecraftfuture                              | 0.1.13                   | future-mc-0.1.13.jar                                      | None      |
       | L     | fxcontrol                                    | 0.1.14                   | fxcontrol-1.12-0.1.14.jar                                 | None      |
       | L     | gamestages                                   | 2.0.123                  | GameStages-1.12.2-2.0.123.jar                             | None      |
       | L     | geographicraft                               | 0.8.7                    | GeographiCraft-1.12-0.8.9b.jar                            | None      |
       | L     | glaretorch                                   | 8.10                     | GlareTorch_Ver.8.11_[MC1.12](forge-1.12-14.21.1.2387).jar | None      |
       | L     | grapplemod                                   | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                               | None      |
       | L     | gbook_snapshot                               | 2.9.1.s5                 | Guidebook-1.12.2-2.9.1.s5.jar                             | None      |
       | L     | hardcoredarkness                             | 2.0                      | HardcoreDarkness-MC1.12.2-2.0.jar                         | None      |
       | L     | helpfixer                                    | 1.12.1-1.5.18            | HelpFixer-1.12.1-1.5.18.jar                               | None      |
       | L     | hw_inv                                       | 1.12.1-1.1.13            | hostileworlds_invasions-1.12.1-1.1.13.jar                 | None      |
       | L     | hungeroverhaul                               | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar                | None      |
       | L     | hungertweaker                                | 1.3.0                    | HungerTweaker-1.12.2-1.3.0.jar                            | None      |
       | L     | waila                                        | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                               | None      |
       | L     | iceandfire                                   | 1.8.4                    | iceandfire-1.8.4.jar                                      | None      |
       | L     | ido                                          | 1.0.6                    | ido-1.12.2-1.1.0.jar                                      | None      |
       | L     | incontrol                                    | 3.9.16                   | incontrol-1.12-3.9.16.jar                                 | None      |
       | L     | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                                  | None      |
       | L     | jei                                          | 4.15.0.293               | jei_1.12.2-4.15.0.293.jar                                 | None      |
       | L     | kleeslabs                                    | 5.4.12                   | KleeSlabs_1.12.2-5.4.12.jar                               | None      |
       | L     | letmesleep                                   | 1.2.1                    | LetMeSleep-v1.2.1-1.12.2.jar                              | None      |
       | L     | libraryex                                    | 1.1.3                    | LibraryEx-1.12.2-1.1.3.jar                                | None      |
       | L     | livingenchantment                            | 3.2.1                    | living_enchantment-3.2.1.jar                              | None      |
       | L     | logimmune                                    | 0.1                      | logimmune-0.1.jar                                         | None      |
       | L     | lttweaker                                    | 1.1.14                   | LootTableTweaker-1.12.2-1.1.14.jar                        | None      |
       | L     | loottweaker                                  | 0.1.7                    | LootTweaker-0.1.7+MC1.12.2.jar                            | None      |
       | L     | magma_monsters                               | 0.3.0                    | MagmaMonsters-0.3.0.jar                                   | None      |
       | L     | materialchanger                              | 1.0                      | materialchanger1.0.3-1.12.2.jar                           | None      |
       | L     | mcwbridges                                   | 1.0.4                    | mcw-bridges-1.0.4-mc1.12.2.jar                            | None      |
       | L     | minerva                                      | 1.0.13                   | minerva-library-1.0.13.jar                                | None      |
       | L     | minetraps                                    | 1.0.4                    | MineTraps-1.12.2-(v.1.0.4).jar                            | None      |
       | L     | testdummy                                    | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                                | None      |
       | L     | mobstages                                    | 2.0.13                   | MobStages-1.12.2-2.0.13.jar                               | None      |
       | L     | modtweaker                                   | 4.0.18                   | modtweaker-4.0.18.jar                                     | None      |
       | L     | guilib                                       | $version                 | morepaintings-paintings-1.12.2-5.0.1.2.jar                | None      |
       | L     | paintingselgui                               | $version                 | morepaintings-paintings-1.12.2-5.0.1.2.jar                | None      |
       | L     | morepaintings                                | $version                 | morepaintings-paintings-1.12.2-5.0.1.2.jar                | None      |
       | L     | msmlegacy                                    | @VERSION@                | MoreSwordsLegacy-1.12.2-1.0.7.jar                         | None      |
       | L     | movingworld                                  | 1.12-6.342               | movingworld-1.12-6.342-full.jar                           | None      |
       | L     | mowziesmobs                                  | 1.5.5                    | mowziesmobs-1.5.5.jar                                     | None      |
       | L     | mtlib                                        | 3.0.6                    | MTLib-3.0.6.jar                                           | None      |
       | L     | multimob                                     | 1.0.5                    | multimob-1.0.5.jar                                        | None      |
       | L     | multithreadednoise                           | 0.0.2                    | MultithreadedNoise-1.12.2-0.0.2.jar                       | None      |
       | L     | mysticallib                                  | 1.12.2-1.7.0             | mysticallib-1.12.2-1.7.0.jar                              | None      |
       | L     | netherchest                                  | 1.1.1                    | netherchest-1.1.1.jar                                     | None      |
       | L     | netherex                                     | 2.1.7                    | NetherEx-1.12.2-2.1.7.jar                                 | None      |
       | L     | netherportalfix                              | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar                         | None      |
       | L     | nyx                                          | 1.3.0                    | Nyx-1.3.0.jar                                             | None      |
       | L     | orespawn                                     | 3.3.1                    | OreSpawn-1.12-3.3.1.179.jar                               | None      |
       | L     | harvestcraft                                 | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zg.jar                           | None      |
       | L     | placebo                                      | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                                  | None      |
       | L     | potioncore                                   | 1.9_for_1.12.2           | PotionCore-1.9_for_1.12.2.jar                             | None      |
       | L     | primitivemobs                                | 1.2.3a                   | primitivemobs-1.2.3a.jar                                  | None      |
       | L     | pyrotech                                     | 1.12.2-1.4.29            | pyrotech-1.12.2-1.4.29.jar                                | None      |
       | L     | qualitytools                                 | 1.0.7_for_1.12.2         | QualityTools-1.0.7_for_1.12.2.jar                         | None      |
       | L     | quark                                        | r1.6-179                 | Quark-r1.6-179.jar                                        | None      |
       | L     | quarkoddities                                | 1                        | QuarkOddities-1.12.2.jar                                  | None      |
       | L     | randomenchantments                           | @VERSION@                | randomenchants-0.1.4a.jar                                 | None      |
       | L     | rats                                         | 3.2.6                    | rats-3.2.6.jar                                            | None      |
       | L     | rebind                                       | 2.7.5                    | rebind-1.12.2-2.7.5-0.jar                                 | None      |
       | L     | sandro                                       | 1.3d                     | Redstone++ ver1.3e.jar                                    | None      |
       | L     | redstoneplusplus                             | 1.3e                     | Redstone++ ver1.3e.jar                                    | None      |
       | L     | redstonepaste                                | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                            | None      |
       | L     | additionalstructures                         | 2.3.1                    | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar          | None      |
       | L     | rockytweaks                                  | 0.6.0-PRE-RELEASE-3      | rockytweaks-1.12.2-0.6.0-PRE-RELEASE-3.jar                | None      |
       | L     | roguelike                                    | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                        | None      |
       | L     | roughmobsrevamped                            | 2.3.16                   | roughmobsrevamped-1.12.2-2.3.16.jar                       | None      |
       | L     | ruins                                        | 17.2                     | Ruins-1.12.2.jar                                          | None      |
       | L     | rustic                                       | 1.1.2                    | rustic-1.1.2.jar                                          | None      |
       | L     | rusticbopwoods                               | 1.0                      | rusticbopwoods-1.0.jar                                    | None      |
       | L     | savemystronghold                             | 1.12.2-1.0.0             | savemystronghold-1.12.2-1.0.0.jar                         | None      |
       | L     | scalinghealth                                | 1.3.37                   | ScalingHealth-1.12.2-1.3.42+147.jar                       | None      |
       | L     | sereneseasons                                | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar                 | None      |
       | L     | setbonus                                     | 1.12.2.019               | SetBonus-1.12.2.019.jar                                   | None      |
       | L     | silentlib                                    | 3.0.13                   | SilentLib-1.12.2-3.0.14+168.jar                           | None      |
       | L     | simplecore                                   | 1.7.3.4                  | simplecore-1.12.2-1.7.3.4.jar                             | None      |
       | L     | simpleores                                   | 1.11.2.2                 | simpleores-1.12.2-1.11.2.2.jar                            | None      |
       | L     | spartancompat                                | @VERSION@                | spartancompat-1.2.2.jar                                   | None      |
       | L     | spartanfire                                  | 0.07                     | spartanfire-0.07.jar                                      | None      |
       | L     | spartanshields                               | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                           | None      |
       | L     | spartanweaponry                              | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar                     | None      |
       | L     | specialai                                    | 1.1.0_for_mc1.12.2       | specialai-1.1.0_for_mc1.12.2.jar                          | None      |
       | L     | specialmobs                                  | 1.0.2_for_mc1.12.2       | specialmobs-1.0.2_for_mc1.12.2.jar                        | None      |
       | L     | stg                                          | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                                      | None      |
       | L     | stygian                                      | 1.0.4                    | stygian-1.0.4.jar                                         | None      |
       | L     | surge                                        | 2.0.79                   | Surge-1.12.2-2.0.79.jar                                   | None      |
       | L     | beneath                                      | 1.7.0                    | The Beneath-1.12.2-1.7.0.jar                              | None      |
       | L     | timekeeping                                  | 2019.3-1.3.2             | timekeeping-1.0.0.jar                                     | None      |
       | L     | toolbelt                                     | 1.9.12                   | ToolBelt-1.12.2-1.9.12.jar                                | None      |
       | L     | toroquest                                    | 1.12.2-5.3               | toroquest-1.12.2-5.3.jar                                  | None      |
       | L     | trashslot                                    | 8.4.10                   | TrashSlot_1.12.2-8.4.10.jar                               | None      |
       | L     | triumph                                      | 3.19.2                   | Triumph-1.12.2-3.19.2.jar                                 | None      |
       | L     | trumpetskeleton                              | 1.12-1.0.2.1             | trumpetskeleton-1.12-1.0.2.1.jar                          | None      |
       | L     | twilightforest                               | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar             | None      |
       | L     | undergroundbiomes                            | 1.3.8                    | UndergroundBiomesConstructs-1.12-1.3.8.jar                | None      |
       | L     | unloader                                     | 1.2.0                    | unloader-1.2.0.jar                                        | None      |
       | L     | vanillaanvilrepair                           | 1.1                      | vanillaanvilrepair-1.1.jar                                | None      |
       | L     | vanillafix                                   | 1.0.10-150               | VanillaFix-1.0.10-150.jar                                 | None      |
       | L     | dimstack                                     | 0.1.9                    | VerticallyStackedDimensions-1.12.2-0.1.9.jar              | None      |
       | L     | villagenames                                 | 3.3.1                    | VillageNames-1.12.2-3.3.1.jar                             | None      |
       | L     | vtt                                          | 0.6.4                    | VillagerTrades-1.12-0.6.4.jar                             | None      |
       | L     | wards                                        | 1.3.1                    | wards-1.3.1.jar                                           | None      |
       | L     | watercontrolextreme                          | 1.0.0                    | WaterControlExtreme-1.0.2.jar                             | None      |
       | L     | weakerspwbs                                  | 1.3                      | weakerspwbs_1.12-1.3.jar                                  | None      |
       | L     | zombie_players                               | 1.12.1-1.2.7             | zombie_players-1.12.1-1.2.7.jar                           | None      |
       | L     | zombieawareness                              | 1.12.1-1.11.16           | zombieawareness-1.12.1-1.11.16.jar                        | None      |
       | L     | orelib                                       | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                                 | None      |
       | L     | totemexpansion                               | 1.2.2                    | totemexpansion-1.2.2-1.12.2.jar                           | None      |
       | L     | toolprogression                              | 1.12.2-1.6.9             | toolprogression-1.12.2-1.6.9.jar                          | None      |
       | L     | quickteleports                               | 1.0                      | quickteleports-1.15.2-1.1.2.jar                           | None      |
       | L     | llibrary                                     | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                                | None      |
       | L     | discordrpc                                   | 1.3.3                    | discordrpc-1.3.3-1.12.jar                                 | None      |
       | L     | betteranimalsplus                            | 9.0.1                    | betteranimalsplus-1.12.2-9.0.1.jar                        | None      |
       | L     | phosphor-lighting                            | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar               | None      |
  Loaded coremods (and transformers): ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.9.jar)
                                        tyra314.toolprogression.core.asm.ToolProgressionClassTransformer
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      EC Core Plugin (enchcontrol-1.12.2-1.1.5-0.jar)
                                        austeretony.enchcontrol.common.core.ECClassTransformer
                                      LoadingPlugin (BetterWithLib-1.12-1.5.jar)
                                        betterwithmods.library.core.ClassTransformer
                                      iceandfire (iceandfire-1.8.4.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      ReBind Core (rebind-1.12.2-2.7.5-0.jar)
                                        austeretony.rebind.common.core.ReBindClassTransformer
                                      Vertically Stacked Dimensions ASM (VerticallyStackedDimensions-1.12.2-0.1.9.jar)
                                        cd4017be.dimstack.asm.ChunkPrimerTransformer
                                        cd4017be.dimstack.asm.BlockPortalTransformer
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      RandomPatches (randompatches-1.12.2-1.21.0.3.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
                                        
                                      Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CharmLoadingPlugin (Charm-1.12.2-1.3.7.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      FutureMC (future-mc-0.1.13.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      BNBGamingCore (BNBGamingCore-1.12.2-0.11.0.jar)
                                        com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCoreClassTransformer
                                      ratscore (rats-3.2.6.jar)
                                        com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      MovingWorldCore (movingworld-1.12-6.342-full.jar)
                                        
                                      AALoadingPlugin (arcanearchives-0.2.0.19.jar)
  Suspected Mods: Unknown
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server

**Crash Log 2**

**Info (please complete the following information):**
 - Modpack Version:  Lastest
 - Server or Singleplayer: Server
 - Version the world was created on:  Latest

**Additional context**

**Comment by democat3457** [comment]
Self-explanatory. You installed a mod called quickteleports for MC version 1.15.2. Also, try not to use "Latest" when describing versions - for all we know, you could not know that there was a newer version.

**Comment by democat3457** [comment]
Additionally, we generally do not support tweaked installs because the bug/crash could be caused by a mod conflict from one of the added/removed mods - such as this one.

**Comment by CallMeDaBest** [comment]
Wait the crash report was from yesterday and I already deleted that mod but currently all the players on my server get 'Timed Out" but there are no crash reports or errors in the console. It's like we all get taken out the server but in the console, it shows nothing has happened at all but we cant join back until I restart the server

**Comment by democat3457** [comment]
What happens after you restart the server? Also did you port-forward and network correctly?

**Comment by CallMeDaBest** [comment]
the server is fine for like 15 minutes then all the players get 'Timed Out' again... I use SkyNode so I'm guessing it does the port-forward and network for me

**Comment by democat3457** [comment]
Closing due to inactivity.
