### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by Ambiramus** [Rebirth-of-the-Night/Rebirth-Of-The-Night#441]
**Describe the crash**

When I try to launch the pack, it crashes. It does not produce a log as it never actually opens. The log posted is latest.log.

**To Reproduce**
Click on play after Twitch opens the Minecraft launcher. 

**Crash Log**

[03:14:07] [main/INFO]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[03:14:07] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Timmonds Ross\Twitch\Minecraft\Install\runtime\jre-x64
[03:14:17] [main/WARN]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[03:14:17] [main/WARN]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[03:14:17] [main/INFO]: Searching C:\Users\Timmonds Ross\Twitch\Minecraft\Instances\Rebirth of the Night\mods for mods
[03:14:17] [main/INFO]: Searching C:\Users\Timmonds Ross\Twitch\Minecraft\Instances\Rebirth of the Night\mods\1.12.2 for mods
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.4.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[03:14:17] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from arcanearchives-0.2.0.19.jar
[03:14:17] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in BetterWithLib-1.12-1.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod LoadingPlugin (betterwithmods.library.core.LoadingPlugin) is not signed!
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Blur-1.0.4-14.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod com.tterrag.blur.BlurPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:17] [main/WARN]: The coremod BlurPlugin (com.tterrag.blur.BlurPlugin) is not signed!
[03:14:17] [main/WARN]: The coremod com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:17] [main/WARN]: The coremod BNBGamingCore (com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin) is not signed!
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Born In A Barn V1.8-1.12-1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod com.chocohead.biab.BornInABarn does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:17] [main/WARN]: The coremod Born in a Barn (com.chocohead.biab.BornInABarn) is not signed!
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Charm-1.12.2-1.3.7.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod svenhjol.charm.base.CharmLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:17] [main/WARN]: The coremod CharmLoadingPlugin (svenhjol.charm.base.CharmLoadingPlugin) is not signed!
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ChunkAnimator-MC1.12-1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod lumien.chunkanimator.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:17] [main/WARN]: The coremod LoadingPlugin (lumien.chunkanimator.asm.LoadingPlugin) is not signed!
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.2.31.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:17] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CustomLoadingScreen-1.12.2-1.4.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod ClsPlugin (alexiil.mc.mod.load.coremod.ClsPlugin) is not signed!
[03:14:17] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.1.0.jar
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in enchcontrol-1.12.2-1.1.5-0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.10-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:17] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in future-mc-0.1.13.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod FutureMC (thedarkcolour.futuremc.asm.CoreLoader) is not signed!
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in HardcoreDarkness-MC1.12.2-2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod lumien.hardcoredarkness.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:17] [main/WARN]: The coremod iceandfire (com.github.alexthe666.iceandfire.asm.IceAndFirePlugin) is not signed!
[03:14:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:18] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:18] [main/WARN]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:18] [main/WARN]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[03:14:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from movingworld-1.12-6.342-full.jar
[03:14:18] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F5.jar
[03:14:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-179.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:18] [main/WARN]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[03:14:18] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in rats-3.2.6.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:18] [main/WARN]: The coremod ratscore (com.github.alexthe666.rats.server.asm.RatsPlugin) is not signed!
[03:14:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in rebind-1.12.2-2.7.5-0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in redstonepaste-mc1.12-1.7.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:18] [main/WARN]: The coremod net.fybertech.nwr.NWRTweak does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:18] [main/WARN]: The coremod NWRTweak (net.fybertech.nwr.NWRTweak) is not signed!
[03:14:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:18] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in SereneSeasons-1.12.2-1.2.18-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:18] [main/WARN]: The coremod sereneseasons.asm.SSLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:18] [main/WARN]: The coremod SSLoadingPlugin (sereneseasons.asm.SSLoadingPlugin) is not signed!
[03:14:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in SmoothFont-mc1.12.2-2.1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:18] [main/WARN]: The coremod bre.smoothfont.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:18] [main/WARN]: The coremod CorePlugin (bre.smoothfont.asm.CorePlugin) is not signed!
[03:14:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Surge-1.12.2-2.0.79.jar
[03:14:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-150.jar
[03:14:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in VerticallyStackedDimensions-1.12.2-0.1.9.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[03:14:18] [main/WARN]: The coremod Vertically Stacked Dimensions ASM (cd4017be.dimstack.asm.CorePlugin) is not signed!
[03:14:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.6+build50-universal.jar
[03:14:18] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:14:18] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[03:14:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Timmonds%20Ross/Twitch/Minecraft/Instances/Rebirth%20of%20the%20Night/mods/arcanearchives-0.2.0.19.jar Service=LaunchWrapper Env=CLIENT
[03:14:18] [main/DEBUG]: Instantiating coremod class AALoadingPlugin
[03:14:18] [main/DEBUG]: The coremod com.aranaira.arcanearchives.core.AALoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[03:14:18] [main/WARN]: The coremod AALoadingPlugin (com.aranaira.arcanearchives.core.AALoadingPlugin) is not signed!
[03:14:18] [main/INFO]: Attempting to bootstrap Mixins and plugins.
[03:14:18] [main/INFO]: Compatibility level set to JAVA_8
[03:14:18] [main/DEBUG]: Enqueued coremod AALoadingPlugin
[03:14:18] [main/DEBUG]: Instantiating coremod class TransformLoader
[03:14:18] [main/DEBUG]: The coremod org.orecruncher.dsurround.mixins.TransformLoader requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[03:14:18] [main/DEBUG]: Found signing certificates for coremod TransformLoader (org.orecruncher.dsurround.mixins.TransformLoader)
[03:14:18] [main/DEBUG]: Found certificate 7a2128d395ad96ceb9d9030fbd41d035b435753a
[03:14:18] [main/DEBUG]: Enqueued coremod TransformLoader
[03:14:18] [main/DEBUG]: Instantiating coremod class MovingWorldCoreMod
[03:14:18] [main/TRACE]: coremod named MovingWorldCore is loading
[03:14:18] [main/WARN]: The coremod com.elytradev.movingworld.common.asm.coremod.MovingWorldCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[03:14:18] [main/WARN]: The coremod MovingWorldCore (com.elytradev.movingworld.common.asm.coremod.MovingWorldCoreMod) is not signed!
[03:14:18] [main/ERROR]: Mixin config mixins.movingworld.json does not specify "minVersion" property
[03:14:18] [main/DEBUG]: Enqueued coremod MovingWorldCore
[03:14:18] [main/DEBUG]: Instantiating coremod class SurgeLoadingPlugin
[03:14:19] [main/DEBUG]: The coremod net.darkhax.surge.core.SurgeLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[03:14:19] [main/DEBUG]: Found signing certificates for coremod SurgeLoadingPlugin (net.darkhax.surge.core.SurgeLoadingPlugin)
[03:14:19] [main/DEBUG]: Found certificate d476d1b22b218a10d845928d1665d45fce301b27
[03:14:19] [main/DEBUG]: Enqueued coremod SurgeLoadingPlugin
[03:14:19] [main/DEBUG]: Instantiating coremod class VanillaFixLoadingPlugin
[03:14:19] [main/INFO]: Initializing VanillaFix
[03:14:19] [main/INFO]: Initializing StacktraceDeobfuscator
[03:14:19] [main/INFO]: Found MCP method mappings: methods-stable_39.csv
[03:14:19] [main/INFO]: Done initializing StacktraceDeobfuscator
[03:14:19] [main/INFO]: Initializing Bug Fix Mixins
[03:14:19] [main/INFO]: Initializing Crash Fix Mixins
[03:14:19] [main/INFO]: Initializing Profiler Improvement Mixins
[03:14:19] [main/INFO]: Initializing Texture Fix Mixins
[03:14:19] [main/INFO]: Initializing Mod Support Mixins
[03:14:19] [main/DEBUG]: The coremod org.dimdev.vanillafix.VanillaFixLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[03:14:19] [main/WARN]: The coremod VanillaFixLoadingPlugin (org.dimdev.vanillafix.VanillaFixLoadingPlugin) is not signed!
[03:14:19] [main/DEBUG]: Enqueued coremod VanillaFixLoadingPlugin
[03:14:19] [main/DEBUG]: Instantiating coremod class PhosphorFMLLoadingPlugin
[03:14:19] [main/DEBUG]: The coremod me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[03:14:19] [main/DEBUG]: Found signing certificates for coremod PhosphorFMLLoadingPlugin (me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin)
[03:14:19] [main/DEBUG]: Found certificate f0387d288626cc2d937daa504e74af570c52a2f1
[03:14:19] [main/DEBUG]: Enqueued coremod PhosphorFMLLoadingPlugin
[03:14:19] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[03:14:19] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[03:14:19] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[03:14:19] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[03:14:19] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[03:14:19] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[03:14:19] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[03:14:19] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[03:14:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:14:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[03:14:19] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[03:14:19] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[03:14:19] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[03:14:19] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[03:14:19] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\Timmonds Ross\Twitch\Minecraft\Instances\Rebirth of the Night\mods\OptiFine_1.12.2_HD_U_F5.jar
[03:14:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[03:14:19] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[03:14:19] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[03:14:19] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[03:14:19] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[03:14:19] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[03:14:19] [main/DEBUG]: Injection complete
[03:14:19] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[03:14:19] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[03:14:21] [main/FATAL]: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
[03:14:21] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:169) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:114) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:77) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:187) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:164) ~[forge-1.12.2-14.23.5.2847.jar:?]
	... 2 more
[03:14:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[03:14:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[03:14:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[03:14:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[03:14:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[03:14:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[03:14:21] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Info (please complete the following information):**
 - Modpack Version:  2.77.5
 - Server or Singleplayer: N/A
 - Version the world was created on: N/A

**Additional context**

**Comment by democat3457** [comment]
Reinstall Minecraft, your vanilla MC jar is corrupt.
