### ISSUE TITLE
3.0.2 Server Crashes on Startup[CRASH]

### ISSUE THREAD

**Issue by CrimsonVengeance** [Rebirth-of-the-Night/Rebirth-Of-The-Night#568]
**Describe the crash**
Upon running the start server.bat for 3.0.2 the first time, the server runs for about 2 seconds and crashes.

**To Reproduce**
Download the server pack, change the IP, and run the start server.
**Crash Log**
[16:25:36] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at C:\Users\Owner\Desktop\Rebirth+of+the+Night+3.0+BETA+2+SERVER\. for Forge Mod Loader
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:87) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:47) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:62) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2854.jar:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_231]
        at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2854.jar:?]
        ... 11 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: modsDir.listFiles() returned null! Attempted to index: \Users\Owner\Desktop\Rebirth of the Night 3.0 BETA 2 SERVER\.\mods
        at com.github.terminatornl.tickcentral.loading.Loader.findTransformersInJarFiles(Loader.java:137) ~[Loader.class:3.2]
        at com.github.terminatornl.tickcentral.loading.Loader.<init>(Loader.java:38) ~[Loader.class:3.2]
        at com.github.terminatornl.tickcentral.TickCentral.<clinit>(TickCentral.java:37) ~[TickCentral-3.2.jar:3.2]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_231]
        at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2854.jar:?]
        ... 11 more
Caused by: java.lang.IllegalStateException: modsDir.listFiles() returned null! Attempted to index: \Users\Owner\Desktop\Rebirth of the Night 3.0 BETA 2 SERVER\.\mods
        at com.github.terminatornl.tickcentral.loading.Loader.findTransformersInJarFiles(Loader.java:121) ~[Loader.class:3.2]
        at com.github.terminatornl.tickcentral.loading.Loader.<init>(Loader.java:38) ~[Loader.class:3.2]
        at com.github.terminatornl.tickcentral.TickCentral.<clinit>(TickCentral.java:37) ~[TickCentral-3.2.jar:3.2]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_231]
        at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2854.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2854.jar:?]
        ... 11 more
A problem occurred running the Server launcher.[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: java.lang.reflect.InvocationTargetException
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at java.lang.reflect.Method.invoke(Unknown Source)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at java.lang.SecurityManager.checkExit(Unknown Source)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at java.lang.Runtime.exit(Unknown Source)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at java.lang.System.exit(Unknown Source)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:25:36] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        ... 6 more

**Info (please complete the following information):**
 - Modpack Version: 3.0.2
 - Server:
 - Version the world was created on:
never got that far.
**Additional context**

When i looked up the issue, it said that the server might have a version of a mod above the Minecraft version.

**Comment by democat3457** [comment]
Change the spaces in the server filename from `+` to ` `

**Comment by CrimsonVengeance** [comment]
That worked, thank you!
