### ISSUE TITLE
the game crashes from the launcher[CRASH]

### ISSUE THREAD

**Issue by DaniilMinecraft1** [Rebirth-of-the-Night/Rebirth-Of-The-Night#829]
### Describe the crash

I want to play assembly , and when I want to go into the game itself , after loading the launcher , it starts loading minecraft ( the icon does not appear yet ) and crashes into the launcher with a crash

### Crash Logs

[20:59:08] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:59:08] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:59:08] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:59:08] [main/INFO]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[20:59:08] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-legacy\windows-x64\jre-legacy
[20:59:08] [main/WARN]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[20:59:08] [main/WARN]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[20:59:08] [main/INFO]: Searching C:\Users\zhanna\AppData\Roaming\.minecraft\mods for mods
[20:59:08] [main/INFO]: Searching C:\Users\zhanna\AppData\Roaming\.minecraft\mods\1.12.2 for mods
[20:59:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.4.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:08] [main/WARN]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[20:59:08] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from arcanearchives-0.2.0.19.jar
[20:59:08] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[20:59:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in BetterWithLib-1.12-1.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:08] [main/WARN]: The coremod LoadingPlugin (betterwithmods.library.core.LoadingPlugin) is not signed!
[20:59:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Blur-1.0.4-14.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:08] [main/WARN]: The coremod com.tterrag.blur.BlurPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:08] [main/WARN]: The coremod BlurPlugin (com.tterrag.blur.BlurPlugin) is not signed!
[20:59:08] [main/WARN]: The coremod com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:08] [main/WARN]: The coremod BNBGamingCore (com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin) is not signed!
[20:59:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Born In A Barn V1.8-1.12-1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:08] [main/WARN]: The coremod com.chocohead.biab.BornInABarn does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:08] [main/WARN]: The coremod Born in a Barn (com.chocohead.biab.BornInABarn) is not signed!
[20:59:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Charm-1.12.2-1.3.7.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:08] [main/WARN]: The coremod svenhjol.charm.base.CharmLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:08] [main/WARN]: The coremod CharmLoadingPlugin (svenhjol.charm.base.CharmLoadingPlugin) is not signed!
[20:59:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ChunkAnimator-MC1.12-1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:08] [main/WARN]: The coremod lumien.chunkanimator.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:08] [main/WARN]: The coremod LoadingPlugin (lumien.chunkanimator.asm.LoadingPlugin) is not signed!
[20:59:08] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.2.31.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:09] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CustomLoadingScreen-1.12.2-1.4.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod ClsPlugin (alexiil.mc.mod.load.coremod.ClsPlugin) is not signed!
[20:59:09] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.1.0.jar
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in enchcontrol-1.12.2-1.1.5-0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.10-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:09] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in future-mc-0.1.13.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod FutureMC (thedarkcolour.futuremc.asm.CoreLoader) is not signed!
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in HardcoreDarkness-MC1.12.2-2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod lumien.hardcoredarkness.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod iceandfire (com.github.alexthe666.iceandfire.asm.IceAndFirePlugin) is not signed!
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:09] [main/WARN]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:09] [main/WARN]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[20:59:09] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from movingworld-1.12-6.342-full.jar
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-179.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[20:59:09] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in rats-3.2.6.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod ratscore (com.github.alexthe666.rats.server.asm.RatsPlugin) is not signed!
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in rebind-1.12.2-2.7.5-0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in redstonepaste-mc1.12-1.7.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod net.fybertech.nwr.NWRTweak does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:09] [main/WARN]: The coremod NWRTweak (net.fybertech.nwr.NWRTweak) is not signed!
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in SereneSeasons-1.12.2-1.2.18-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod sereneseasons.asm.SSLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:09] [main/WARN]: The coremod SSLoadingPlugin (sereneseasons.asm.SSLoadingPlugin) is not signed!
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in SmoothFont-mc1.12.2-2.1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod bre.smoothfont.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:09] [main/WARN]: The coremod CorePlugin (bre.smoothfont.asm.CorePlugin) is not signed!
[20:59:09] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Surge-1.12.2-2.0.79.jar
[20:59:09] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-150.jar
[20:59:09] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in VerticallyStackedDimensions-1.12.2-0.1.9.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:59:09] [main/WARN]: The coremod Vertically Stacked Dimensions ASM (cd4017be.dimstack.asm.CorePlugin) is not signed!
[20:59:09] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.6+build50-universal.jar
[20:59:09] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:59:09] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[20:59:09] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/zhanna/AppData/Roaming/.minecraft/mods/arcanearchives-0.2.0.19.jar Service=LaunchWrapper Env=CLIENT
[20:59:09] [main/DEBUG]: Instantiating coremod class AALoadingPlugin
[20:59:09] [main/DEBUG]: The coremod com.aranaira.arcanearchives.core.AALoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[20:59:09] [main/WARN]: The coremod AALoadingPlugin (com.aranaira.arcanearchives.core.AALoadingPlugin) is not signed!
[20:59:09] [main/INFO]: Attempting to bootstrap Mixins and plugins.
[20:59:09] [main/INFO]: Compatibility level set to JAVA_8
[20:59:09] [main/DEBUG]: Enqueued coremod AALoadingPlugin
[20:59:10] [main/DEBUG]: Instantiating coremod class TransformLoader
[20:59:10] [main/DEBUG]: The coremod org.orecruncher.dsurround.mixins.TransformLoader requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[20:59:10] [main/DEBUG]: Found signing certificates for coremod TransformLoader (org.orecruncher.dsurround.mixins.TransformLoader)
[20:59:10] [main/DEBUG]: Found certificate 7a2128d395ad96ceb9d9030fbd41d035b435753a
[20:59:10] [main/DEBUG]: Enqueued coremod TransformLoader
[20:59:10] [main/DEBUG]: Instantiating coremod class MovingWorldCoreMod
[20:59:10] [main/TRACE]: coremod named MovingWorldCore is loading
[20:59:10] [main/WARN]: The coremod com.elytradev.movingworld.common.asm.coremod.MovingWorldCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:59:10] [main/WARN]: The coremod MovingWorldCore (com.elytradev.movingworld.common.asm.coremod.MovingWorldCoreMod) is not signed!
[20:59:10] [main/ERROR]: Mixin config mixins.movingworld.json does not specify "minVersion" property
[20:59:10] [main/DEBUG]: Enqueued coremod MovingWorldCore
[20:59:10] [main/DEBUG]: Instantiating coremod class SurgeLoadingPlugin
[20:59:10] [main/DEBUG]: The coremod net.darkhax.surge.core.SurgeLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[20:59:10] [main/DEBUG]: Found signing certificates for coremod SurgeLoadingPlugin (net.darkhax.surge.core.SurgeLoadingPlugin)
[20:59:10] [main/DEBUG]: Found certificate d476d1b22b218a10d845928d1665d45fce301b27
[20:59:10] [main/DEBUG]: Enqueued coremod SurgeLoadingPlugin
[20:59:10] [main/DEBUG]: Instantiating coremod class VanillaFixLoadingPlugin
[20:59:10] [main/INFO]: Initializing VanillaFix
[20:59:10] [main/INFO]: Initializing StacktraceDeobfuscator
[20:59:10] [main/INFO]: Found MCP method mappings: methods-stable_39.csv
[20:59:10] [main/INFO]: Done initializing StacktraceDeobfuscator
[20:59:10] [main/INFO]: Initializing Bug Fix Mixins
[20:59:10] [main/INFO]: Initializing Crash Fix Mixins
[20:59:10] [main/INFO]: Initializing Profiler Improvement Mixins
[20:59:10] [main/INFO]: Initializing Texture Fix Mixins
[20:59:10] [main/INFO]: Initializing Mod Support Mixins
[20:59:10] [main/DEBUG]: The coremod org.dimdev.vanillafix.VanillaFixLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[20:59:10] [main/WARN]: The coremod VanillaFixLoadingPlugin (org.dimdev.vanillafix.VanillaFixLoadingPlugin) is not signed!
[20:59:10] [main/DEBUG]: Enqueued coremod VanillaFixLoadingPlugin
[20:59:10] [main/DEBUG]: Instantiating coremod class PhosphorFMLLoadingPlugin
[20:59:10] [main/DEBUG]: The coremod me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[20:59:10] [main/DEBUG]: Found signing certificates for coremod PhosphorFMLLoadingPlugin (me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin)
[20:59:10] [main/DEBUG]: Found certificate f0387d288626cc2d937daa504e74af570c52a2f1
[20:59:10] [main/DEBUG]: Enqueued coremod PhosphorFMLLoadingPlugin
[20:59:10] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[20:59:10] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[20:59:10] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[20:59:10] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[20:59:10] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[20:59:10] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[20:59:10] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:59:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:59:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:59:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:59:10] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[20:59:10] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[20:59:10] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[20:59:10] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[20:59:10] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[20:59:10] [main/DEBUG]: Injection complete
[20:59:10] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[20:59:10] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[20:59:12] [main/FATAL]: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
[20:59:12] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:169) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:114) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:77) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:187) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:164) ~[forge-1.12.2-14.23.5.2847.jar:?]
	... 2 more
[20:59:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[20:59:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[20:59:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[20:59:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[20:59:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[20:59:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[20:59:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Modpack Version

3.0.0

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.0.0

### Additional context

absolutely do not understand what happened already 3 hours spent in nowhere._.

**Comment by democat3457** [comment]
Try reinstalling

**Comment by DaniilMinecraft1** [comment]
I can try it more than once except from other sites

**Comment by DaniilMinecraft1** [comment]
[](https://translate.yandex.ru/)I have already tried it and more than once I can only try it from other sites

**Comment by DaniilMinecraft1** [comment]
> Попробуйте переустановить


I've already tried it from different sites now I'm going to try to download beta suddenly on it I can

**Comment by democat3457** [comment]
did you get it to work?

**Comment by DaniilMinecraft1** [comment]
> вы заставили его работать?

no the build didn't start working no matter what I did

**Comment by democat3457** [comment]
you may have to reinstall forge or the launcher

**Comment by democat3457** [comment]
also since this issue is 4 months old
